pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
  plugins {
    id "org.jetbrains.kotlin.kapt" version '2.3.21'
    id "org.jetbrains.kotlin.plugin.lombok" version '2.3.21'
  }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'music-spring'
include 'musicbackend'
include 'musicfrontend'
include 'musicandroid'
include 'musicandroid:app'
include 'helm'
