import './01_verify-api-spec.cy.ts'
import './02_add-tracks.cy.ts'
import './03_verify-directory-locations.cy.ts'
import './04_search-for-track.cy.ts'
import './05_classify-some-tracks.cy.ts'
import './06_create-playlist-from-mixer.cy.ts'
import './07_play_audio.cy.ts'
import './08_save_and_restore_tracks.cy.ts'
