spring.application.name=musicbackend

server.port=8002
spring.profiles.active=qa

# CORS configuration
app.cors.allowed-origins=http://localhost:4200

# Database Configuration (Matches index.html)
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

# Feedback: Show SQL statements in the log as they happen
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.hibernate.SQL=DEBUG
