spring.application.name=musicbackend

spring.config.import=optional:classpath:initial-data.yml,${SPRING_CONFIG_IMPORT_EXTRA:}

server.port=8002

# CORS configuration
app.cors.allowed-origins=http://localhost:4200,http://octan:8010

# Actuator / Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Path to music folder
# This is the path that the app sees. If it is running in a container
# and you have mounted a volume, it is the directory of the volume
# inside the container
app.music-directory=/mp3

