# PostgreSQL connection for local development
spring.datasource.url=jdbc:postgresql://localhost:5432/musicdb
spring.datasource.username=musicuser
spring.datasource.password=musicpass

# Configuration from the 'qa' profile needed for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=musicdatabase
spring.datasource.hikari.connection-init-sql=SET search_path TO musicdatabase, public

# Path to local music folder for bootRun tasks
# This is the path that the app sees. If it is running in a container
# and you have mounted a volume, it is the directory of the volume
# inside the container
#app.music-directory=/richi/ToDo/tryout/mp3
app.music-directory=/richi/mp3
