spring.application.name=musicbackend

spring.config.import=optional:classpath:initial-data.yml,${SPRING_CONFIG_IMPORT_EXTRA:}

server.port=8002

# CORS configuration
app.cors.allowed-origins=http://localhost:4200,http://octan:8010

# Actuator / Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Database configuration
spring.jpa.hibernate.ddl-auto=update

# Multipart configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Path to music folder
# This is the path that the app sees. If it is running in a container
# and you have mounted a volume, it is the directory of the volume
# inside the container
app.music-directory=/mp3

# Database dump paths for startup sync
app.db.sql-dump-path=/richi/ToDo/music_db.sql
app.db.json-dump-path=/richi/ToDo/music.json
