apiVersion: v1
kind: Service
metadata:
  name: music-backend
  labels:
    app: music-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: music-backend
