apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-frontend
  labels:
    app: music-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: music-frontend
  template:
    metadata:
      labels:
        app: music-frontend
    spec:
      containers:
        - name: music-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.env.port }}
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: {{ .Values.frontend.env.backendUrl | quote }}
            - name: PORT
              value: {{ .Values.frontend.env.port | quote }}
